### ISSUE TITLE
Missing script?

### ISSUE THREAD

**Issue by dza6549** [ShadedSelf/Old-UnityGPGPU#1]
Hi @ShadedSelf 

I found this repo via UnityList. Is it intended to be public? I'd love to get it working. I'm using 2018.3. There's a script missing on the Experiments GO in the RAY scene.

If you weren't planning on offering any support or if this was a private repo - no worries. 

It does look great and would love to see something like this animated.

Cheers

**Comment by ShadedSelf** [comment]
Hey @dza6549
 
The metadata was removed to make the repo readable.
This is supposed to be a sort portfolio.
I've readded the associated *.meta files anyways, you should be able to import the project now.

**Comment by dza6549** [comment]
@ShadedSelf Thanks for your reply. I've downloaded the latest repo and it runs but I'm not sure what to do next.

I run the RAY scene and I get this. It moves! :)

![RAY](https://user-images.githubusercontent.com/27390320/54792726-777b8d00-4c93-11e9-9526-5d46d8287f1e.png)

then I run the sh scene and I get this

![sh](https://user-images.githubusercontent.com/27390320/54792750-967a1f00-4c93-11e9-8f5f-a2881b2fe79a.png)

I also get 17 shader warnings. I'm using 2018.3 on Win 10

![warning](https://user-images.githubusercontent.com/27390320/54792773-ad207600-4c93-11e9-9c04-bfdc102ac6ca.png)

I'm guessing I need to connect the 2 scenes somehow so the shader is on the falling bricks? Please let me know if I am missing something.

This is really great looking. Maybe you should record some video for your portfolio and put it on Reddit, etc? Maybe you know about Unity video Recorder already? https://assetstore.unity.com/packages/essentials/unity-recorder-94079

Cheers

**Comment by ShadedSelf** [comment]
@dza6549 
For the fluid sim you are gonna need a small enough delta, aka high framerate, for it to be stable, try messing with the parameters and disabling the main camera.

For the other scene you can use the editor camera to move around, it will affect the game view.
